# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2


_PYTHONREQUESTMSG_SENSORTYPE = descriptor.EnumDescriptor(
  name='SensorType',
  full_name='LTLMoPCsharpInterface.PythonRequestMsg.SensorType',
  filename='SensorType',
  values=[
    descriptor.EnumValueDescriptor(
      name='NOSENSOR', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LIDAR', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ARTAG', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OPENDOOR', index=3, number=3,
      options=None,
      type=None),
  ],
  options=None,
)

_PYTHONREQUESTMSG_ACTUATORTYPE = descriptor.EnumDescriptor(
  name='ActuatorType',
  full_name='LTLMoPCsharpInterface.PythonRequestMsg.ActuatorType',
  filename='ActuatorType',
  values=[
    descriptor.EnumValueDescriptor(
      name='NOACT', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ARM', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EXPLORE', index=2, number=2,
      options=None,
      type=None),
  ],
  options=None,
)

_PYTHONREQUESTMSG_ACTUATORSTATUS = descriptor.EnumDescriptor(
  name='ActuatorStatus',
  full_name='LTLMoPCsharpInterface.PythonRequestMsg.ActuatorStatus',
  filename='ActuatorStatus',
  values=[
    descriptor.EnumValueDescriptor(
      name='RESP_IDLE', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RESP_BUSY', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REQ_UPDATE', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REQ_DO', index=3, number=3,
      options=None,
      type=None),
  ],
  options=None,
)

_PYTHONREQUESTMSG_ROBOTTYPE = descriptor.EnumDescriptor(
  name='RobotType',
  full_name='LTLMoPCsharpInterface.PythonRequestMsg.RobotType',
  filename='RobotType',
  values=[
    descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PIONEER', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SEGWAY', index=2, number=2,
      options=None,
      type=None),
  ],
  options=None,
)

_PYTHONREQUESTMSG_MAPTYPE = descriptor.EnumDescriptor(
  name='MapType',
  full_name='LTLMoPCsharpInterface.PythonRequestMsg.MapType',
  filename='MapType',
  values=[
    descriptor.EnumValueDescriptor(
      name='NEWREGIONFOUND', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REGIONUPDATE', index=1, number=1,
      options=None,
      type=None),
  ],
  options=None,
)


_PYTHONREQUESTMSG_VELOCITY = descriptor.Descriptor(
  name='Velocity',
  full_name='LTLMoPCsharpInterface.PythonRequestMsg.Velocity',
  filename='ltlmopMsg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='v', full_name='LTLMoPCsharpInterface.PythonRequestMsg.Velocity.v', index=0,
      number=1, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='omega', full_name='LTLMoPCsharpInterface.PythonRequestMsg.Velocity.omega', index=1,
      number=2, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_PYTHONREQUESTMSG_ACTUATOR = descriptor.Descriptor(
  name='Actuator',
  full_name='LTLMoPCsharpInterface.PythonRequestMsg.Actuator',
  filename='ltlmopMsg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='actuatorType', full_name='LTLMoPCsharpInterface.PythonRequestMsg.Actuator.actuatorType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status', full_name='LTLMoPCsharpInterface.PythonRequestMsg.Actuator.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='LTLMoPCsharpInterface.PythonRequestMsg.Actuator.data', index=2,
      number=3, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_PYTHONREQUESTMSG_POINT = descriptor.Descriptor(
  name='Point',
  full_name='LTLMoPCsharpInterface.PythonRequestMsg.Point',
  filename='ltlmopMsg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='x', full_name='LTLMoPCsharpInterface.PythonRequestMsg.Point.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='y', full_name='LTLMoPCsharpInterface.PythonRequestMsg.Point.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_PYTHONREQUESTMSG_REGION = descriptor.Descriptor(
  name='Region',
  full_name='LTLMoPCsharpInterface.PythonRequestMsg.Region',
  filename='ltlmopMsg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='points', full_name='LTLMoPCsharpInterface.PythonRequestMsg.Region.points', index=0,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='holes', full_name='LTLMoPCsharpInterface.PythonRequestMsg.Region.holes', index=1,
      number=3, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='LTLMoPCsharpInterface.PythonRequestMsg.Region.name', index=2,
      number=4, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='area', full_name='LTLMoPCsharpInterface.PythonRequestMsg.Region.area', index=3,
      number=5, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_PYTHONREQUESTMSG_MAP = descriptor.Descriptor(
  name='Map',
  full_name='LTLMoPCsharpInterface.PythonRequestMsg.Map',
  filename='ltlmopMsg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='r', full_name='LTLMoPCsharpInterface.PythonRequestMsg.Map.r', index=0,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='LTLMoPCsharpInterface.PythonRequestMsg.Map.type', index=1,
      number=3, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_PYTHONREQUESTMSG_FACE = descriptor.Descriptor(
  name='Face',
  full_name='LTLMoPCsharpInterface.PythonRequestMsg.Face',
  filename='ltlmopMsg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='p1', full_name='LTLMoPCsharpInterface.PythonRequestMsg.Face.p1', index=0,
      number=2, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='p2', full_name='LTLMoPCsharpInterface.PythonRequestMsg.Face.p2', index=1,
      number=3, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_PYTHONREQUESTMSG_EXTERNALFACES = descriptor.Descriptor(
  name='ExternalFaces',
  full_name='LTLMoPCsharpInterface.PythonRequestMsg.ExternalFaces',
  filename='ltlmopMsg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='faces', full_name='LTLMoPCsharpInterface.PythonRequestMsg.ExternalFaces.faces', index=0,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_PYTHONREQUESTMSG_POSE = descriptor.Descriptor(
  name='Pose',
  full_name='LTLMoPCsharpInterface.PythonRequestMsg.Pose',
  filename='ltlmopMsg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='x', full_name='LTLMoPCsharpInterface.PythonRequestMsg.Pose.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='y', full_name='LTLMoPCsharpInterface.PythonRequestMsg.Pose.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='yaw', full_name='LTLMoPCsharpInterface.PythonRequestMsg.Pose.yaw', index=2,
      number=3, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_PYTHONREQUESTMSG_SENSOR = descriptor.Descriptor(
  name='Sensor',
  full_name='LTLMoPCsharpInterface.PythonRequestMsg.Sensor',
  filename='ltlmopMsg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='LTLMoPCsharpInterface.PythonRequestMsg.Sensor.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stat', full_name='LTLMoPCsharpInterface.PythonRequestMsg.Sensor.stat', index=1,
      number=2, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='LTLMoPCsharpInterface.PythonRequestMsg.Sensor.data', index=2,
      number=3, type=1, cpp_type=5, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_PYTHONREQUESTMSG = descriptor.Descriptor(
  name='PythonRequestMsg',
  full_name='LTLMoPCsharpInterface.PythonRequestMsg',
  filename='ltlmopMsg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='LTLMoPCsharpInterface.PythonRequestMsg.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='robot', full_name='LTLMoPCsharpInterface.PythonRequestMsg.robot', index=1,
      number=2, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='vel', full_name='LTLMoPCsharpInterface.PythonRequestMsg.vel', index=2,
      number=3, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='actuator', full_name='LTLMoPCsharpInterface.PythonRequestMsg.actuator', index=3,
      number=4, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sensor', full_name='LTLMoPCsharpInterface.PythonRequestMsg.sensor', index=4,
      number=5, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='map', full_name='LTLMoPCsharpInterface.PythonRequestMsg.map', index=5,
      number=7, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pose', full_name='LTLMoPCsharpInterface.PythonRequestMsg.pose', index=6,
      number=8, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='exfaces', full_name='LTLMoPCsharpInterface.PythonRequestMsg.exfaces', index=7,
      number=9, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ResendRequest', full_name='LTLMoPCsharpInterface.PythonRequestMsg.ResendRequest', index=8,
      number=10, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sensors', full_name='LTLMoPCsharpInterface.PythonRequestMsg.sensors', index=9,
      number=11, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _PYTHONREQUESTMSG_SENSORTYPE,
    _PYTHONREQUESTMSG_ACTUATORTYPE,
    _PYTHONREQUESTMSG_ACTUATORSTATUS,
    _PYTHONREQUESTMSG_ROBOTTYPE,
    _PYTHONREQUESTMSG_MAPTYPE,
  ],
  options=None)


_PYTHONREQUESTMSG_ACTUATOR.fields_by_name['actuatorType'].enum_type = _PYTHONREQUESTMSG_ACTUATORTYPE
_PYTHONREQUESTMSG_ACTUATOR.fields_by_name['status'].enum_type = _PYTHONREQUESTMSG_ACTUATORSTATUS
_PYTHONREQUESTMSG_REGION.fields_by_name['points'].message_type = _PYTHONREQUESTMSG_POINT
_PYTHONREQUESTMSG_REGION.fields_by_name['holes'].message_type = _PYTHONREQUESTMSG_POINT
_PYTHONREQUESTMSG_MAP.fields_by_name['r'].message_type = _PYTHONREQUESTMSG_REGION
_PYTHONREQUESTMSG_MAP.fields_by_name['type'].enum_type = _PYTHONREQUESTMSG_MAPTYPE
_PYTHONREQUESTMSG_FACE.fields_by_name['p1'].message_type = _PYTHONREQUESTMSG_POINT
_PYTHONREQUESTMSG_FACE.fields_by_name['p2'].message_type = _PYTHONREQUESTMSG_POINT
_PYTHONREQUESTMSG_EXTERNALFACES.fields_by_name['faces'].message_type = _PYTHONREQUESTMSG_FACE
_PYTHONREQUESTMSG_SENSOR.fields_by_name['type'].enum_type = _PYTHONREQUESTMSG_SENSORTYPE
_PYTHONREQUESTMSG.fields_by_name['robot'].enum_type = _PYTHONREQUESTMSG_ROBOTTYPE
_PYTHONREQUESTMSG.fields_by_name['vel'].message_type = _PYTHONREQUESTMSG_VELOCITY
_PYTHONREQUESTMSG.fields_by_name['actuator'].message_type = _PYTHONREQUESTMSG_ACTUATOR
_PYTHONREQUESTMSG.fields_by_name['sensor'].enum_type = _PYTHONREQUESTMSG_SENSORTYPE
_PYTHONREQUESTMSG.fields_by_name['map'].message_type = _PYTHONREQUESTMSG_MAP
_PYTHONREQUESTMSG.fields_by_name['pose'].message_type = _PYTHONREQUESTMSG_POSE
_PYTHONREQUESTMSG.fields_by_name['exfaces'].message_type = _PYTHONREQUESTMSG_EXTERNALFACES
_PYTHONREQUESTMSG.fields_by_name['sensors'].message_type = _PYTHONREQUESTMSG_SENSOR

class PythonRequestMsg(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Velocity(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PYTHONREQUESTMSG_VELOCITY
  
  class Actuator(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PYTHONREQUESTMSG_ACTUATOR
  
  class Point(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PYTHONREQUESTMSG_POINT
  
  class Region(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PYTHONREQUESTMSG_REGION
  
  class Map(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PYTHONREQUESTMSG_MAP
  
  class Face(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PYTHONREQUESTMSG_FACE
  
  class ExternalFaces(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PYTHONREQUESTMSG_EXTERNALFACES
  
  class Pose(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PYTHONREQUESTMSG_POSE
  
  class Sensor(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PYTHONREQUESTMSG_SENSOR
  DESCRIPTOR = _PYTHONREQUESTMSG

